CREATE TABLE users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_name VARCHAR(255),
   password VARCHAR(255),
   role INT,
   CONSTRAINT pk_users PRIMARY KEY (user_id)
);

INSERT INTO users (user_name, password, role) VALUES ('seller', 'seller123', 1);
INSERT INTO users (user_name, password, role) VALUES ('manager', 'manager123', 0);
